#define DUCKDB_EXTENSION_MAIN

#include "opendal_extension.hpp"
#include "duckdb.hpp"
#include "duckdb/common/exception.hpp"
#include "duckdb/function/scalar_function.hpp"
#include "duckdb/main/database.hpp"
#include <duckdb/parser/parsed_data/create_scalar_function_info.hpp>

#include "opendal_filesystem.hpp"
#include "opendal_table_functions.hpp"
#include "opendal_secret.hpp"

#include "duckdb/main/database.hpp"
#include "duckdb/main/config.hpp"
#include "duckdb/main/setting_info.hpp"

// FFI surface of the OpenDAL Rust core (duckdb-opendal), generated by cbindgen.
#include "rust.h"

#include <string>

namespace duckdb {

// Callback for the `opendal_override_native_filesystems` setting: updates the
// set of schemes for which opendal wins DuckDB's VFS dispatch over native
// extensions (e.g. httpfs's s3://).
static void SetOverrideNativeFilesystems(ClientContext &, SetScope, Value &parameter) {
	OpenDalFileSystem::SetOverrideSchemes(parameter.IsNull() ? std::string() : parameter.ToString());
}

static std::map<std::string, std::string> ConfigMap(const Value &value) {
	std::map<std::string, std::string> result;
	if (value.IsNull()) {
		return result;
	}
	for (auto &entry : ListValue::GetChildren(value)) {
		auto &kv = StructValue::GetChildren(entry);
		if (kv.size() == 2) {
			result[kv[0].ToString()] = kv[1].ToString();
		}
	}
	return result;
}

static void SetIoConfig(ClientContext &, SetScope, Value &v) {
	OpenDalFileSystem::SetGlobalConfig("io", ConfigMap(v));
}
static void SetRetryConfig(ClientContext &, SetScope, Value &v) {
	OpenDalFileSystem::SetGlobalConfig("retry", ConfigMap(v));
}
static void SetTimeoutConfig(ClientContext &, SetScope, Value &v) {
	OpenDalFileSystem::SetGlobalConfig("timeout", ConfigMap(v));
}
static void SetCacheConfig(ClientContext &, SetScope, Value &v) {
	OpenDalFileSystem::SetGlobalConfig("cache", ConfigMap(v));
}

// opendal_version() -> VARCHAR
// Format: "opendal <ext-version> (built with opendal-core <opendal-lib-version>)".
//   <ext-version>          this extension's build/git version — the same value
//                          duckdb_extensions().extension_version reports
//                          (EXT_VERSION_OPENDAL, set by the build).
//   <opendal-lib-version>  the linked OpenDAL crate version, resolved from
//                          Cargo.toml at build time (od_opendal_version()).
inline void OpendalVersionScalarFun(DataChunk &args, ExpressionState &state, Vector &result) {
	char *raw = od_opendal_version();
	std::string opendal_lib = raw ? std::string(raw) : std::string("unknown");
	if (raw) {
		od_string_free(raw); // ownership crossed the boundary; free it here
	}
#ifdef EXT_VERSION_OPENDAL
	std::string ext_version = EXT_VERSION_OPENDAL;
#else
	std::string ext_version = "unknown";
#endif
	std::string version = "opendal " + ext_version + " (built with opendal-core " + opendal_lib + ")";
	result.SetVectorType(VectorType::CONSTANT_VECTOR);
	result.SetValue(0, Value(version));
}

static void LoadInternal(ExtensionLoader &loader) {
	auto &db = loader.GetDatabaseInstance();

	// One-time init of the Rust core: populate OpenDAL's service registry and
	// install the rustls (ring) crypto provider + reqwest HTTP transport. Must
	// run before any operator is built (idempotent).
	od_init();

	// Register the OpenDAL filesystem as a DuckDB subsystem. From here, any URL
	// with a supported OpenDAL scheme (fs://, memory://, …) is served through
	// the Rust core. Keep a raw pointer (owned by the VFS) for table functions.
	auto fs_uptr = make_uniq<OpenDalFileSystem>();
	auto *fs_ptr = fs_uptr.get();
	db.GetFileSystem().RegisterSubSystem(std::move(fs_uptr));

	// opendal_version() — returns the linked duckdb-opendal / OpenDAL version.
	auto version_fn = ScalarFunction("opendal_version", {}, LogicalType::VARCHAR, OpendalVersionScalarFun);
	loader.RegisterFunction(version_fn);

	// Table functions: opendal_ls(), opendal_stat(), opendal_du().
	RegisterOpenDalTableFunctions(loader, fs_ptr);

	// CREATE SECRET support for the OpenDAL service schemes (SCOPE-matched).
	RegisterOpenDalSecrets(loader);

	// Setting: opendal_override_native_filesystems — comma-separated schemes for
	// which opendal should win over native/core extensions (e.g. httpfs's
	// s3://). Empty (default) = no override; native handlers keep precedence.
	db.config.AddExtensionOption(
	    "opendal_override_native_filesystems",
	    "Comma-separated schemes (e.g. 's3,gcs') for which the OpenDAL filesystem overrides native "
	    "extensions in DuckDB's filesystem dispatch. Empty disables all overrides.",
	    LogicalType::VARCHAR, Value(""), SetOverrideNativeFilesystems);

	auto map_type = LogicalType::MAP(LogicalType::VARCHAR, LogicalType::VARCHAR);
	db.config.AddExtensionOption("opendal_io_config", "Global OpenDAL reader/writer options.", map_type, Value(),
	                             SetIoConfig, SetScope::GLOBAL);
	db.config.AddExtensionOption("opendal_retry_config", "Global OpenDAL retry-layer options.", map_type, Value(),
	                             SetRetryConfig, SetScope::GLOBAL);
	db.config.AddExtensionOption("opendal_timeout_config", "Global OpenDAL timeout-layer options.", map_type, Value(),
	                             SetTimeoutConfig, SetScope::GLOBAL);
	db.config.AddExtensionOption("opendal_cache_config", "Global OpenDAL data-cache options.", map_type, Value(),
	                             SetCacheConfig, SetScope::GLOBAL);
}

void OpendalExtension::Load(ExtensionLoader &loader) {
	LoadInternal(loader);
}
std::string OpendalExtension::Name() {
	return "opendal";
}

std::string OpendalExtension::Version() const {
#ifdef EXT_VERSION_OPENDAL
	return EXT_VERSION_OPENDAL;
#else
	return "";
#endif
}

} // namespace duckdb

extern "C" {

DUCKDB_CPP_EXTENSION_ENTRY(opendal, loader) {
	duckdb::LoadInternal(loader);
}
}
