#ifndef DUCKDB_OPENDAL_RUST_H
#define DUCKDB_OPENDAL_RUST_H

#pragma once

/* Warning: this file is autogenerated by cbindgen. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error categories surfaced to the C++ side. Mirrors the subset of
 * `opendal::ErrorKind` we care about; everything else collapses to `Other`.
 */
typedef enum OdErrorCode {
    Ok = 0,
    NotFound = 1,
    PermissionDenied = 2,
    NotADirectory = 3,
    IsADirectory = 4,
    AlreadyExists = 5,
    InvalidInput = 6,
    Unsupported = 7,
    Unexpected = 8,
    /**
     * A Rust panic was caught at the FFI boundary.
     */
    Panic = 98,
    /**
     * Anything not otherwise categorized.
     */
    Other = 99,
} OdErrorCode;

/**
 * Opaque, index-addressable list of an operator's boolean capabilities.
 */
typedef struct OdCapabilityList OdCapabilityList;

/**
 * Opaque, index-addressable list of entries.
 *
 * `Entry::path()`/`name()` return non-NUL-terminated `&str`, so we lazily build
 * and cache NUL-terminated `CString`s (whose lifetime matches the list) the
 * first time an entry is requested. The cache lives in an `UnsafeCell` because
 * entry access takes `&self` at the FFI layer; access is single-threaded per
 * call (one DuckDB worker owns the list handle at a time).
 */
typedef struct OdEntryList OdEntryList;

/**
 * Opaque handle wrapping an `opendal::Operator`.
 */
typedef struct OdOperator OdOperator;

/**
 * Opaque handle wrapping an `opendal::Reader`. Free with `od_reader_free`.
 */
typedef struct OdReader OdReader;

/**
 * Opaque handle wrapping an `opendal::Writer`.
 */
typedef struct OdWriter OdWriter;

/**
 * C-visible error out-param. Zero-initialized means success.
 *
 * `message` is either null or an owned C string; free it with
 * `od_string_free`.
 */
typedef struct OdError {
    enum OdErrorCode code;
    char *message;
} OdError;

/**
 * One capability flag: `name` (borrowed, NUL-terminated) + `supported`.
 */
typedef struct OdCapability {
    /**
     * Capability name (e.g. "write_can_append"). Borrowed from the list; do
     * NOT free. Valid until `od_capabilities_free`.
     */
    const char *name;
    /**
     * 1 if supported, 0 otherwise.
     */
    uint8_t supported;
} OdCapability;

/**
 * One entry's metadata, returned by value from `od_list_entry`.
 *
 * `path` and `name` are borrowed pointers into the `OdEntryList` and are
 * valid only until the list is freed. The C++ side must copy them out.
 */
typedef struct OdEntry {
    /**
     * Full path of the entry (relative to the operator root), NUL-terminated.
     * Borrowed from the list; do NOT free.
     */
    const char *path;
    /**
     * Base name of the entry, NUL-terminated. Borrowed; do NOT free.
     */
    const char *name;
    uint64_t content_length;
    int64_t last_modified_ms;
    uint8_t is_dir;
} OdEntry;

/**
 * C-visible metadata for a path.
 */
typedef struct OdMetadata {
    /**
     * Content length in bytes.
     */
    uint64_t content_length;
    /**
     * Last-modified time in Unix milliseconds, or -1 if unknown.
     */
    int64_t last_modified_ms;
    /**
     * 1 if this path is a directory, 0 otherwise.
     */
    uint8_t is_dir;
} OdMetadata;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * One-time process initialization — call once at extension load, before any
 * operator is built.
 *
 * Populates OpenDAL's service registry (we link opendal as a `staticlib`, so
 * its `#[ctor]` init can be dropped by the linker) and installs the rustls
 * `ring` crypto provider + reqwest HTTP transport (the `rustls-no-provider`
 * feature auto-installs neither). Idempotent (guarded by a `Once`).
 */
void od_init(void);

/**
 * Return a heap-allocated C string describing the crate + OpenDAL
 * versions. Caller owns the pointer and MUST free it with `od_string_free`.
 *
 * Returns null on allocation failure or panic.
 *
 * # Safety
 * The returned pointer must be freed exactly once via `od_string_free` and
 * not used afterwards.
 */
char *od_version(void);

/**
 * Free a C string previously returned by this library (e.g. `od_version`,
 * or an `OdError::message`).
 *
 * Safe to call with null (no-op).
 *
 * # Safety
 * `ptr` must be either null or a pointer previously returned by this library
 * and not already freed.
 */
void od_string_free(char *ptr);

/**
 * Materialize every boolean capability of `op` into an index-addressable list.
 *
 * Returns null only on null input or panic. Free with
 * `od_capabilities_free`.
 *
 * # Safety
 * `op` must be a live handle from `od_operator_new`. `err` must be valid.
 */
struct OdCapabilityList *od_capabilities(const struct OdOperator *op, struct OdError *err);

/**
 * Number of capability entries in the list. 0 on null.
 *
 * # Safety
 * `list` must be null or a handle from `od_capabilities`.
 */
uintptr_t od_capabilities_len(const struct OdCapabilityList *list);

/**
 * Read capability `index` into `out`. Returns 1 on success, 0 on out-of-range
 * or null. `out.name` borrows from the list (valid until it is freed).
 *
 * # Safety
 * `list` must be a live handle from `od_capabilities`; `out` must be valid.
 */
uint8_t od_capabilities_entry(const struct OdCapabilityList *list,
                              uintptr_t index,
                              struct OdCapability *out);

/**
 * Free a capability list. Safe with null (no-op).
 *
 * # Safety
 * `list` must be null or a handle from `od_capabilities`, not already freed.
 */
void od_capabilities_free(struct OdCapabilityList *list);

/**
 * Set the process-global I/O defaults. A field of `0` means "unset".
 *
 * # Safety
 * Plain scalar FFI; always safe. Panic-guarded by the caller.
 */
void od_set_global_io_options(uintptr_t read_concurrent,
                              uintptr_t read_chunk,
                              uintptr_t write_concurrent,
                              uintptr_t write_chunk);

/**
 * List entries under `path`. When `recursive` is non-zero, descends into
 * subdirectories.
 *
 * On success returns a non-null `*mut OdEntryList` and sets `*err` to Ok.
 *
 * # Safety
 * - `op` must be a live handle from `od_operator_new`.
 * - `path` must be a valid NUL-terminated C string.
 * - The returned handle must be freed once with `od_list_free`.
 */
struct OdEntryList *od_list(const struct OdOperator *op,
                            const char *path,
                            uint8_t recursive,
                            struct OdError *err);

/**
 * Number of entries in the list. Returns 0 if `list` is null.
 *
 * # Safety
 * `list` must be null or a live handle from `od_list`.
 */
uintptr_t od_list_len(const struct OdEntryList *list);

/**
 * Fetch entry `index` into `out`. `path`/`name` in `out` borrow the list and
 * are valid until `od_list_free`. Returns 1 on success, 0 if out of range.
 *
 * # Safety
 * - `list` must be a live handle from `od_list`.
 * - `out` must be a valid, writable pointer.
 * - The returned `path`/`name` pointers must not be used after the list is
 *   freed, and must not be freed themselves.
 */
uint8_t od_list_entry(const struct OdEntryList *list, uintptr_t index, struct OdEntry *out);

/**
 * Free an entry list. Safe to call with null (no-op).
 *
 * # Safety
 * `list` must be null or a handle from `od_list`, not already freed, with no
 * borrowed `path`/`name` pointers still in use.
 */
void od_list_free(struct OdEntryList *list);

/**
 * Create a directory at `path` (recursive, like `mkdir -p`). `path` should end
 * with '/'. Returns 0 on success, -1 on error.
 *
 * # Safety
 * - `op` must be a live handle from `od_operator_new`.
 * - `path` must be a valid NUL-terminated C string.
 */
int32_t od_create_dir(const struct OdOperator *op, const char *path, struct OdError *err);

/**
 * Remove a file or (recursively) a directory at `path`. Returns 0 on success,
 * -1 on error.
 *
 * # Safety
 * - `op` must be a live handle from `od_operator_new`.
 * - `path` must be a valid NUL-terminated C string.
 */
int32_t od_remove(const struct OdOperator *op,
                  const char *path,
                  uint8_t recursive,
                  struct OdError *err);

/**
 * Rename/move `from` to `to` within the same operator. Returns 0 on success,
 * -1 on error. Not all services support server-side rename.
 *
 * # Safety
 * - `op` must be a live handle from `od_operator_new`.
 * - `from`/`to` must be valid NUL-terminated C strings.
 */
int32_t od_rename(const struct OdOperator *op,
                  const char *from,
                  const char *to,
                  struct OdError *err);

/**
 * Copy `from` to `to` within the same operator. Returns 0 on success, -1 on
 * error. Guarded on the `copy` capability. Used by the C++ `MoveFile`
 * copy+delete fallback when a service lacks server-side `rename` (e.g. s3).
 *
 * # Safety
 * - `op` must be a live handle from `od_operator_new`.
 * - `from`/`to` must be valid NUL-terminated C strings.
 */
int32_t od_copy(const struct OdOperator *op, const char *from, const char *to, struct OdError *err);

/**
 * Build an Operator from `uri` (`scheme://authority`) plus `len` key/value
 * config pairs, then apply optional layers described by `layer_len` pairs.
 *
 * Construction goes through `Operator::from_uri((uri, extra_opts))`: OpenDAL's
 * per-service URI parsing maps the authority to the right config key (bucket /
 * container / …); `keys`/`values` are extra OpenDAL config (typically a
 * SCOPE-matched secret) that override URI-parsed values.
 * `layer_keys`/`layer_values` configure layers (retry/timeout/… — see
 * `layers.rs`).
 * On success returns a non-null `*mut OdOperator` and sets `*err` to Ok.
 * On failure returns null and populates `*err`.
 *
 * # Safety
 * - `uri`, and each config/layer `keys[i]`/`values[i]`, must be valid
 *   NUL-terminated C strings for the duration of the call.
 * - `keys`/`values` must each point to `len` valid pointers (or be null iff
 *   `len == 0`); likewise `layer_keys`/`layer_values` and `layer_len`.
 * - The returned handle must be freed exactly once with `od_operator_free`.
 */
struct OdOperator *od_operator_new(const char *uri,
                                   const char *const *keys,
                                   const char *const *values,
                                   uintptr_t len,
                                   const char *const *layer_keys,
                                   const char *const *layer_values,
                                   uintptr_t layer_len,
                                   struct OdError *err);

/**
 * Free an operator handle. Safe to call with null (no-op).
 *
 * # Safety
 * `op` must be null or a handle from `od_operator_new`, not already freed,
 * with no live Reader/Lister/etc. still borrowing it.
 */
void od_operator_free(struct OdOperator *op);

/**
 * Open a reader for `path` on `op`.
 *
 * # Safety
 * - `op` must be a live handle from `od_operator_new`.
 * - `path` must be a valid NUL-terminated C string.
 * - The returned handle must be freed once with `od_reader_free`.
 */
struct OdReader *od_reader_open(const struct OdOperator *op, const char *path, struct OdError *err);

/**
 * Read up to `len` bytes starting at `offset` into `buf`.
 *
 * Returns the number of bytes read (may be less than `len` at EOF), or -1 on
 * error. Reads straight into the caller's buffer.
 *
 * # Safety
 * - `reader` must be a live handle from `od_reader_open`.
 * - `buf` must point to at least `len` writable bytes.
 * - `err` must be a valid, writable pointer.
 */
int64_t od_reader_read(struct OdReader *reader,
                       uint64_t offset,
                       uint64_t len,
                       uint8_t *buf,
                       struct OdError *err);

/**
 * Free a reader handle. Safe to call with null (no-op).
 *
 * # Safety
 * `reader` must be null or a handle from `od_reader_open`, not already freed.
 */
void od_reader_free(struct OdReader *reader);

/**
 * Stat `path` on `op`, writing metadata into `out_meta`.
 *
 * On success sets `*err` to Ok and fills `*out_meta`. On failure populates
 * `*err` and leaves `*out_meta` zeroed.
 *
 * # Safety
 * - `op` must be a live handle from `od_operator_new`.
 * - `path` must be a valid NUL-terminated C string.
 * - `out_meta` and `err` must be valid, writable pointers.
 */
void od_stat(const struct OdOperator *op,
             const char *path,
             struct OdMetadata *out_meta,
             struct OdError *err);

/**
 * Check whether `path` exists. Returns 1 if it exists, 0 if not, -1 on error
 * (with `*err` populated).
 *
 * # Safety
 * - `op` must be a live handle from `od_operator_new`.
 * - `path` must be a valid NUL-terminated C string.
 * - `err` must be a valid, writable pointer.
 */
int8_t od_exists(const struct OdOperator *op, const char *path, struct OdError *err);

/**
 * Open a writer for `path` on `op`. Any existing object at `path` is
 * overwritten on close.
 *
 * # Safety
 * - `op` must be a live handle from `od_operator_new`.
 * - `path` must be a valid NUL-terminated C string.
 * - The returned handle must be freed once with `od_writer_free`.
 */
struct OdWriter *od_writer_open(const struct OdOperator *op, const char *path, struct OdError *err);

/**
 * Append `len` bytes from `data` to the writer. Returns 0 on success, -1 on
 * error.
 *
 * # Safety
 * - `writer` must be a live handle from `od_writer_open`.
 * - `data` must point to at least `len` readable bytes.
 */
int32_t od_writer_write(struct OdWriter *writer,
                        const uint8_t *data,
                        uint64_t len,
                        struct OdError *err);

/**
 * Finalize the writer, flushing all buffered data (and completing any
 * multipart upload). Returns 0 on success, -1 on error. The writer must still
 * be freed with `od_writer_free` afterwards.
 *
 * # Safety
 * `writer` must be a live handle from `od_writer_open`.
 */
int32_t od_writer_close(struct OdWriter *writer, struct OdError *err);

/**
 * Abort the writer, discarding buffered data (and cancelling any multipart
 * upload). Returns 0 on success, -1 on error.
 *
 * # Safety
 * `writer` must be a live handle from `od_writer_open`.
 */
int32_t od_writer_abort(struct OdWriter *writer, struct OdError *err);

/**
 * Free a writer handle. Safe to call with null (no-op). Does NOT flush — call
 * `od_writer_close` first to persist data.
 *
 * # Safety
 * `writer` must be null or a handle from `od_writer_open`, not already freed.
 */
void od_writer_free(struct OdWriter *writer);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DUCKDB_OPENDAL_RUST_H */
