#define DUCKDB_EXTENSION_MAIN

#include "opendal_fs_extension.hpp"
#include "duckdb.hpp"
#include "duckdb/common/exception.hpp"
#include "duckdb/function/scalar_function.hpp"
#include "duckdb/main/database.hpp"
#include <duckdb/parser/parsed_data/create_scalar_function_info.hpp>

#include "opendal_filesystem.hpp"
#include "opendal_table_functions.hpp"
#include "opendal_secret.hpp"

#include "duckdb/main/database.hpp"
#include "duckdb/main/config.hpp"
#include "duckdb/main/setting_info.hpp"

// FFI surface of the OpenDAL Rust core (opendalfs-core), generated by cbindgen.
#include "rust.h"

#include <string>

namespace duckdb {

// Callback for the `opendal_override_native_filesystems` setting: updates the
// set of schemes for which opendal_fs wins DuckDB's VFS dispatch over native
// extensions (e.g. httpfs's s3://).
static void SetOverrideNativeFilesystems(ClientContext &, SetScope, Value &parameter) {
	OpenDalFileSystem::SetOverrideSchemes(parameter.IsNull() ? std::string() : parameter.ToString());
}

// Process-global I/O tuning defaults, mirrored to the Rust core. Each setting's
// callback re-pushes the full set (the FFI takes all four at once). 0 = unset
// (OpenDAL per-service default).
static uint64_t g_io_read_concurrent = 0;
static uint64_t g_io_read_chunk = 0;
static uint64_t g_io_write_concurrent = 0;
static uint64_t g_io_write_chunk = 0;

static void PushGlobalIoOptions() {
	odop_set_global_io_options(g_io_read_concurrent, g_io_read_chunk, g_io_write_concurrent, g_io_write_chunk);
}
static void SetIoReadConcurrent(ClientContext &, SetScope, Value &v) {
	g_io_read_concurrent = v.IsNull() ? 0 : (uint64_t)v.GetValue<int64_t>();
	PushGlobalIoOptions();
}
static void SetIoReadChunk(ClientContext &, SetScope, Value &v) {
	g_io_read_chunk = v.IsNull() ? 0 : (uint64_t)v.GetValue<int64_t>();
	PushGlobalIoOptions();
}
static void SetIoWriteConcurrent(ClientContext &, SetScope, Value &v) {
	g_io_write_concurrent = v.IsNull() ? 0 : (uint64_t)v.GetValue<int64_t>();
	PushGlobalIoOptions();
}
static void SetIoWriteChunk(ClientContext &, SetScope, Value &v) {
	g_io_write_chunk = v.IsNull() ? 0 : (uint64_t)v.GetValue<int64_t>();
	PushGlobalIoOptions();
}

// opendal_fs_version() -> VARCHAR
// Returns the linked opendalfs-core crate version and the resolved OpenDAL
// library version (the latter is not exposed by DuckDB's built-in
// extension_version, which reports this extension's own version). The OpenDAL
// version is resolved from Cargo.lock at build time — see opendalfs-core/build.rs.
inline void OpendalFsVersionScalarFun(DataChunk &args, ExpressionState &state, Vector &result) {
	char *raw = odop_version();
	std::string version = raw ? std::string(raw) : std::string("<unavailable>");
	if (raw) {
		odop_string_free(raw); // ownership crossed the boundary; free it here
	}
	result.SetVectorType(VectorType::CONSTANT_VECTOR);
	result.SetValue(0, Value(version));
}

static void LoadInternal(ExtensionLoader &loader) {
	auto &db = loader.GetDatabaseInstance();

	// Register the OpenDAL filesystem as a DuckDB subsystem. From here, any URL
	// with a supported OpenDAL scheme (fs://, memory://, …) is served through
	// the Rust core. Keep a raw pointer (owned by the VFS) for table functions.
	auto fs_uptr = make_uniq<OpenDalFileSystem>();
	auto *fs_ptr = fs_uptr.get();
	db.GetFileSystem().RegisterSubSystem(std::move(fs_uptr));

	// opendal_fs_version() — returns the linked opendalfs-core / OpenDAL version.
	auto version_fn = ScalarFunction("opendal_fs_version", {}, LogicalType::VARCHAR, OpendalFsVersionScalarFun);
	loader.RegisterFunction(version_fn);

	// Table functions: opendal_ls(), opendal_stat(), opendal_du().
	RegisterOpenDalTableFunctions(loader, fs_ptr);

	// CREATE SECRET support for the OpenDAL service schemes (SCOPE-matched).
	RegisterOpenDalSecrets(loader);

	// Setting: opendal_override_native_filesystems — comma-separated schemes for
	// which opendal_fs should win over native/core extensions (e.g. httpfs's
	// s3://). Empty (default) = no override; native handlers keep precedence.
	db.config.AddExtensionOption(
	    "opendal_override_native_filesystems",
	    "Comma-separated schemes (e.g. 's3,gcs') for which the OpenDAL filesystem overrides native "
	    "extensions in DuckDB's filesystem dispatch. Empty disables all overrides.",
	    LogicalType::VARCHAR, Value(""), SetOverrideNativeFilesystems);

	// Global I/O tuning (applied to every operator unless a secret sets its own
	// io.* option). concurrent = parallel range reads / multipart writes; chunk
	// = per-request size in bytes. 0 (default) = OpenDAL per-service default.
	db.config.AddExtensionOption("opendal_read_concurrent",
	                             "Global default for concurrent range reads (0 = service default).",
	                             LogicalType::BIGINT, Value::BIGINT(0), SetIoReadConcurrent);
	db.config.AddExtensionOption("opendal_read_chunk", "Global default read chunk size in bytes (0 = service default).",
	                             LogicalType::BIGINT, Value::BIGINT(0), SetIoReadChunk);
	db.config.AddExtensionOption("opendal_write_concurrent",
	                             "Global default for concurrent multipart writes (0 = service default).",
	                             LogicalType::BIGINT, Value::BIGINT(0), SetIoWriteConcurrent);
	db.config.AddExtensionOption("opendal_write_chunk",
	                             "Global default write chunk size in bytes (0 = service default).", LogicalType::BIGINT,
	                             Value::BIGINT(0), SetIoWriteChunk);
}

void OpendalFsExtension::Load(ExtensionLoader &loader) {
	LoadInternal(loader);
}
std::string OpendalFsExtension::Name() {
	return "opendal_fs";
}

std::string OpendalFsExtension::Version() const {
#ifdef EXT_VERSION_OPENDAL_FS
	return EXT_VERSION_OPENDAL_FS;
#else
	return "";
#endif
}

} // namespace duckdb

extern "C" {

DUCKDB_CPP_EXTENSION_ENTRY(opendal_fs, loader) {
	duckdb::LoadInternal(loader);
}
}
