#define DUCKDB_EXTENSION_MAIN

#include "opendal_fs_extension.hpp"
#include "duckdb.hpp"
#include "duckdb/common/exception.hpp"
#include "duckdb/function/scalar_function.hpp"
#include "duckdb/main/database.hpp"
#include <duckdb/parser/parsed_data/create_scalar_function_info.hpp>

#include "opendal_filesystem.hpp"

// FFI surface of the OpenDAL Rust core (opendalfs-core), generated by cbindgen.
#include "rust.h"

#include <string>

namespace duckdb {

// opendal_fs_version() -> VARCHAR
// Proves the C++ shell can call into the Rust core across the FFI boundary and
// manage the returned owned C string.
inline void OpendalFsVersionScalarFun(DataChunk &args, ExpressionState &state, Vector &result) {
	char *raw = odop_version();
	std::string version = raw ? std::string(raw) : std::string("<unavailable>");
	if (raw) {
		odop_string_free(raw); // ownership crossed the boundary; free it here
	}
	result.SetVectorType(VectorType::CONSTANT_VECTOR);
	result.SetValue(0, Value(version));
}

static void LoadInternal(ExtensionLoader &loader) {
	auto &db = loader.GetDatabaseInstance();

	// Register the OpenDAL filesystem as a DuckDB subsystem. From here, any URL
	// with a supported OpenDAL scheme (fs://, memory://, …) is served through
	// the Rust core.
	db.GetFileSystem().RegisterSubSystem(make_uniq<OpenDalFileSystem>());

	// opendal_fs_version() — returns the linked opendalfs-core / OpenDAL version.
	auto version_fn =
	    ScalarFunction("opendal_fs_version", {}, LogicalType::VARCHAR, OpendalFsVersionScalarFun);
	loader.RegisterFunction(version_fn);
}

void OpendalFsExtension::Load(ExtensionLoader &loader) {
	LoadInternal(loader);
}
std::string OpendalFsExtension::Name() {
	return "opendal_fs";
}

std::string OpendalFsExtension::Version() const {
#ifdef EXT_VERSION_OPENDAL_FS
	return EXT_VERSION_OPENDAL_FS;
#else
	return "";
#endif
}

} // namespace duckdb

extern "C" {

DUCKDB_CPP_EXTENSION_ENTRY(opendal_fs, loader) {
	duckdb::LoadInternal(loader);
}
}
