#pragma once

#include "duckdb/common/file_system.hpp"
#include "duckdb/common/file_opener.hpp"
#include "duckdb/common/open_file_info.hpp"

#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>

// FFI surface of the OpenDAL Rust core (generated by cbindgen).
#include "rust.h"

// Windows SDK defines CreateDirectory/RemoveDirectory/MoveFile as macros.
#ifdef CreateDirectory
#undef CreateDirectory
#endif
#ifdef RemoveDirectory
#undef RemoveDirectory
#endif
#ifdef MoveFile
#undef MoveFile
#endif

namespace duckdb {

// ─────────────────────────────────────────────────────────────────────────────
// OpenDalFileSystem
//
// A single DuckDB FileSystem subclass that serves every OpenDAL service scheme
// (fs://, memory://, s3://, …). It is registered once with DuckDB's
// VirtualFileSystem and delegates all I/O to the OpenDAL Rust core over the FFI.
//
// Phase 1 scope: read path only (memory + fs) — OpenFile(read)/Read/GetFileSize/
// FileExists/Seek. Writes, listing, glob, mutations, secrets and layers arrive
// in later phases.
// ─────────────────────────────────────────────────────────────────────────────
class OpenDalFileSystem : public FileSystem {
public:
	OpenDalFileSystem();
	~OpenDalFileSystem() override;

	// ── DuckDB FileSystem interface (read path) ─────────────────────────────
	unique_ptr<FileHandle> OpenFile(const string &path, FileOpenFlags flags,
	                                optional_ptr<FileOpener> opener = nullptr) override;

	void Read(FileHandle &handle, void *buffer, int64_t nr_bytes, idx_t location) override;
	int64_t Read(FileHandle &handle, void *buffer, int64_t nr_bytes) override;

	void Write(FileHandle &handle, void *buffer, int64_t nr_bytes, idx_t location) override;
	int64_t Write(FileHandle &handle, void *buffer, int64_t nr_bytes) override;
	void FileSync(FileHandle &handle) override;

	int64_t GetFileSize(FileHandle &handle) override;
	timestamp_t GetLastModifiedTime(FileHandle &handle) override;
	FileType GetFileType(FileHandle &handle) override;

	bool FileExists(const string &filename, optional_ptr<FileOpener> opener = nullptr) override;
	bool DirectoryExists(const string &directory, optional_ptr<FileOpener> opener = nullptr) override;

	bool ListFiles(const string &directory, const std::function<void(const string &, bool)> &callback,
	               FileOpener *opener = nullptr) override;

	// ── Mutations ───────────────────────────────────────────────────────────
	void CreateDirectory(const string &directory, optional_ptr<FileOpener> opener = nullptr) override;
	void RemoveDirectory(const string &directory, optional_ptr<FileOpener> opener = nullptr) override;
	void RemoveFile(const string &filename, optional_ptr<FileOpener> opener = nullptr) override;
	void MoveFile(const string &source, const string &target,
	              optional_ptr<FileOpener> opener = nullptr) override;

	void Seek(FileHandle &handle, idx_t location) override;
	idx_t SeekPosition(FileHandle &handle) override;

	// Phase 1: only exact (non-wildcard) paths are resolved; true globbing
	// arrives with the lister in Phase 2.
	vector<OpenFileInfo> Glob(const string &path, FileOpener *opener = nullptr) override;

	bool CanHandleFile(const string &path) override;
	bool CanSeek() override {
		return true;
	}
	bool OnDiskFile(FileHandle &handle) override;

	string GetName() const override {
		return "OpenDalFileSystem";
	}
	string PathSeparator(const string &path) override {
		return "/";
	}

	// ── Helpers exposed for table functions (ls/stat/du) ────────────────────
	// Parse a URL into scheme + authority + OpenDAL-relative path. Returns false
	// if the URL has no supported scheme.
	bool ParsePublic(const std::string &url, std::string &out_scheme, std::string &out_authority,
	                 std::string &out_path);
	// Rebuild a URL from scheme + authority + OpenDAL entry path.
	static std::string BuildUrlPublic(const std::string &scheme, const std::string &authority,
	                                  const std::string &entry_path) {
		return BuildUrl(scheme, authority, entry_path);
	}
	// Get (creating/caching) an operator for a (scheme, authority) using a
	// ClientContext for secret lookup (table functions). Throws on failure.
	OdopOperator *OperatorForPublic(const std::string &scheme, const std::string &authority,
	                                const std::string &url, optional_ptr<ClientContext> context) {
		return OperatorForCtx(scheme, authority, url, context);
	}
	static bool IsSupportedSchemePublic(const std::string &scheme);

private:
	// Split a URL into scheme, authority (bucket/host — may be empty), and the
	// OpenDAL-relative path. For object stores (s3), the authority is the bucket
	// and the path is the object key; for fs/memory the authority is empty.
	// Returns false if the URL has no recognized scheme.
	static bool ParseUrl(const std::string &url, std::string &out_scheme, std::string &out_authority,
	                     std::string &out_path);

	// Rebuild a full "scheme://[authority/]path" URL from parts, inverting the
	// fs absolutization so results round-trip back through OpenFile.
	static std::string BuildUrl(const std::string &scheme, const std::string &authority,
	                            const std::string &entry_path);

	// Get (creating + caching if needed) an operator handle for a (scheme,
	// authority) pair. `url` is the full request URL (used for SCOPE-matched
	// secret lookup); `opener`/`context` provide access to the SecretManager.
	// Throws IOException on failure.
	OdopOperator *OperatorFor(const std::string &scheme, const std::string &authority,
	                          const std::string &url, optional_ptr<FileOpener> opener);
	OdopOperator *OperatorForCtx(const std::string &scheme, const std::string &authority,
	                             const std::string &url, optional_ptr<ClientContext> context);
	// Shared operator construction: resolve secret + env config, apply layers,
	// cache per scheme://authority.
	OdopOperator *BuildOperator(const std::string &scheme, const std::string &authority,
	                            const std::string &url, optional_ptr<ClientContext> context,
	                            optional_ptr<DatabaseInstance> db);

	std::unordered_map<std::string, OdopOperator *> operators_;
	std::mutex mu_;
};

// ─────────────────────────────────────────────────────────────────────────────
// OpenDalFileHandle — wraps an opaque OpenDAL reader + cached metadata.
// ─────────────────────────────────────────────────────────────────────────────
class OpenDalFileHandle : public FileHandle {
public:
	OpenDalFileHandle(FileSystem &fs, const std::string &path, FileOpenFlags flags,
	                  OdopReader *reader, int64_t file_size, int64_t last_modified_ms);
	// Write-mode handle: wraps an OpenDAL writer.
	OpenDalFileHandle(FileSystem &fs, const std::string &path, FileOpenFlags flags, OdopWriter *writer);
	~OpenDalFileHandle() override;

	void Close() override;

	// Read state.
	OdopReader *reader = nullptr;
	int64_t file_size = 0;
	int64_t position = 0;
	int64_t last_modified_ms = -1;

	// Write state (append-only streaming).
	OdopWriter *writer = nullptr;
	int64_t bytes_written = 0;
	bool write_closed = false;
};

} // namespace duckdb
