#pragma once

#include "duckdb/common/file_system.hpp"
#include "duckdb/common/open_file_info.hpp"

#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>

// FFI surface of the OpenDAL Rust core (generated by cbindgen).
#include "rust.h"

// Windows SDK defines CreateDirectory/RemoveDirectory/MoveFile as macros.
#ifdef CreateDirectory
#undef CreateDirectory
#endif
#ifdef RemoveDirectory
#undef RemoveDirectory
#endif
#ifdef MoveFile
#undef MoveFile
#endif

namespace duckdb {

// ─────────────────────────────────────────────────────────────────────────────
// OpenDalFileSystem
//
// A single DuckDB FileSystem subclass that serves every OpenDAL service scheme
// (fs://, memory://, s3://, …). It is registered once with DuckDB's
// VirtualFileSystem and delegates all I/O to the OpenDAL Rust core over the FFI.
//
// Phase 1 scope: read path only (memory + fs) — OpenFile(read)/Read/GetFileSize/
// FileExists/Seek. Writes, listing, glob, mutations, secrets and layers arrive
// in later phases.
// ─────────────────────────────────────────────────────────────────────────────
class OpenDalFileSystem : public FileSystem {
public:
	OpenDalFileSystem();
	~OpenDalFileSystem() override;

	// ── DuckDB FileSystem interface (read path) ─────────────────────────────
	unique_ptr<FileHandle> OpenFile(const string &path, FileOpenFlags flags,
	                                optional_ptr<FileOpener> opener = nullptr) override;

	void Read(FileHandle &handle, void *buffer, int64_t nr_bytes, idx_t location) override;
	int64_t Read(FileHandle &handle, void *buffer, int64_t nr_bytes) override;

	int64_t GetFileSize(FileHandle &handle) override;
	timestamp_t GetLastModifiedTime(FileHandle &handle) override;
	FileType GetFileType(FileHandle &handle) override;

	bool FileExists(const string &filename, optional_ptr<FileOpener> opener = nullptr) override;
	bool DirectoryExists(const string &directory, optional_ptr<FileOpener> opener = nullptr) override;

	void Seek(FileHandle &handle, idx_t location) override;
	idx_t SeekPosition(FileHandle &handle) override;

	// Phase 1: only exact (non-wildcard) paths are resolved; true globbing
	// arrives with the lister in Phase 2.
	vector<OpenFileInfo> Glob(const string &path, FileOpener *opener = nullptr) override;

	bool CanHandleFile(const string &path) override;
	bool CanSeek() override {
		return true;
	}
	bool OnDiskFile(FileHandle &handle) override;

	string GetName() const override {
		return "OpenDalFileSystem";
	}
	string PathSeparator(const string &path) override {
		return "/";
	}

private:
	// Split a "scheme://rest" URL into its scheme and the OpenDAL-relative path.
	// Returns false if the URL has no recognized scheme.
	static bool ParseUrl(const std::string &url, std::string &out_scheme, std::string &out_path);

	// Get (creating + caching if needed) an operator handle for a scheme.
	// Throws IOException on failure.
	OdopOperator *OperatorForScheme(const std::string &scheme);

	std::unordered_map<std::string, OdopOperator *> operators_;
	std::mutex mu_;
};

// ─────────────────────────────────────────────────────────────────────────────
// OpenDalFileHandle — wraps an opaque OpenDAL reader + cached metadata.
// ─────────────────────────────────────────────────────────────────────────────
class OpenDalFileHandle : public FileHandle {
public:
	OpenDalFileHandle(FileSystem &fs, const std::string &path, FileOpenFlags flags,
	                  OdopReader *reader, int64_t file_size, int64_t last_modified_ms);
	~OpenDalFileHandle() override;

	void Close() override;

	OdopReader *reader = nullptr;
	int64_t file_size = 0;
	int64_t position = 0;
	int64_t last_modified_ms = -1;
};

} // namespace duckdb
